---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1rk2xer6trh7qqh5wm9j3xfaafawpfzrx54sq2rjrkecmd0njz42qg7fzva
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1rk2xer6trh7qqh5wm9j3xfaafawpfzrx54sq2rjrkecmd0njz42qg7fzva
