kind: Secret
ansible_user: ENC[AES256_GCM,data:/9Tj8wY=,iv:m0P6mEuMDFHKm6t5S7eH+1QixfXdTvSQECbRkriJz24=,tag:cw53N6f7AiNppwurkXQE1Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:QwAMcnmMlNPKga4=,iv:3/xbFooL/Xk7m3imUCJIvPjyrPJCaci0w1IlGSb8CxQ=,tag:CMiTDdZNMDvMywDK1IXlhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rk2xer6trh7qqh5wm9j3xfaafawpfzrx54sq2rjrkecmd0njz42qg7fzva
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYUYzZDJMeWJPd1IyalZL
            b1Zyd2FIaWYyZGc1Zm1DeHo4T0FQQ0Q2Wkc4CnFjbzFaR2dsTnZoR1l5dGpidk9a
            UDU2K3hteXpxbys0ZjMwSlVhQ3kvL0kKLS0tIG5lWWRpdXdtYU9UbVhiODNvWXpv
            d25QVmZ6YS9od3Z3VFA3MFZmNERqOTQKedr6KGz7IHYX2llsg2SjzzMU7KepEiF3
            Ss76ylW95xJDj+jWssHq4WyUEHHzdYctY/LlmrdWOlSifhkrCVE3+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-07T23:20:23Z"
    mac: ENC[AES256_GCM,data:HeKWPtpbtHUnucOWYJ0ZwBPscDxKsSTRVGl1fDyx8tLI4ssv9z79jWsKDnuhPlX17/bBYFa3GMbrmigZPrHSQWbrGWgCX34ylBegRX/GCEMGwhK+B39oKTm9BFeahppFy9kscAwyODu8EaspijhLuYr7Z1L3Vomvq8u7MVdGDn0=,iv:CtduVDDlReB5HCubqrmknWplhaktOVle7jlHNsJT9wE=,tag:WV8cNfzWKd6ngaVf6F95DQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
