# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:l3fkb0KwoQAwHNvuE/BnhVkaGMY=,iv:QOO7JztKp1H1X4cjy1OuL5Deop/YS19T1491zeAIc5U=,tag:QJApoM2T51H+T2njN5bY9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rk2xer6trh7qqh5wm9j3xfaafawpfzrx54sq2rjrkecmd0njz42qg7fzva
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtblBYY0hITldVKzlxbi9B
            dCtFTVRMOXFCOW9jWkw0dFg4a1NIM2xvY1RvClpVVVZPQ2ZuZHJTUjVuMGRlY1FQ
            S1FqSWdYelBWcy8wWG53azdNUy9GemMKLS0tIElCSHpJWWNZWEVQamFiU2MwZjlV
            OFVyOENvR21GQS9rQ044NHNhaHZCc2sK2zUQOhtnrmDsHzDNHmH15yDJT9iCgUfh
            UBjrvZ9eZ2kF3+WCG29xOa/bVRZ/8+df7ophF1iG9t+rHhdLOqDnAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-07T23:11:19Z"
    mac: ENC[AES256_GCM,data:l1F6bLlL7m5SV2g/xBfqXQFWykE+CC73amFVcDR0pu13xgA2FBSMWMz4CG+VN70zIMfR5Ab+CQE1uaj1UEuaViWqGbTiHvzmgdgHzmIhhYco92xbbb01V0p/UUwKk7oYS94FwqZKBydk61ZsgVIPG2cPavk7fxqlklWTuktby/w=,iv:xyq3xACGTdNb7mL9u+m+EryjEqTeHKaTuJiXFwpv2iw=,tag:yc/m5w8G8pEHN6S46/YKYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
