# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hd7UnDxT3C0i3MinGN8=,iv:9S0rjkZoaJgLhTJakWGjPLixy2NehpORpywsm+W0mk8=,tag:hdUtqAVv3GxRZwJFLr+FkA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:oluK4YXgnCv5wdbLKBB1ifX9e9c=,iv:hSF9IUJivPBQnpPNDNtK+w3iNYqB+fKSPoaQjZwT36U=,tag:jBLPTo1lyjZ2JoeMh+hF1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rk2xer6trh7qqh5wm9j3xfaafawpfzrx54sq2rjrkecmd0njz42qg7fzva
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WmlwaXFVWTBhcG92QlA2
            TTZQSzhxNXk1NktkU2paRzNtNk9hWHVrZEFjCjd0Sm1RaVFUTW95YmNsRGw5SGp6
            NUJVZHNtVnM5eDZsQm5GTUozdVl6OUkKLS0tIGtGeHR3Y3RnUlFrVlZCdDhaYW96
            T0hBa1BwN00xSEh6cFpVdGl0Y1o3OTQKNLV1qHY/0rGQzbDd1ZjhZjfxR7R1nGr2
            mrFiNKHQH/Gizn2pZ3TVw7ig3QADxaM01DbNnKXvGkMYBu0Sj58O/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-07T20:44:27Z"
    mac: ENC[AES256_GCM,data:FCWa9g1SxTorYpoP6i63aJJ1k/u8ynDBJpqbQ7uNMVvT6bpgMR8c0BsEJn6ryQ2O9PMdkHkGQKmjVH9JpKEpuW3VWI1UJq2CFaBgXsxlj3ZB9xTTSq39p7MZy1gou8plS3549rEC7DRf+vYHbXmvFn4LRCSNgTTj8BKX7D1dalA=,iv:awExN95yv0LGwHzP92KJ0UzAAgsP2vCMeJpAuQV61Xs=,tag:TfyrUdz7IAZYK8Tf3Hq+aw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
